let input =
	{
	"bookunits": "in",
	"bookwidth": 8,
	"bookheight": 8,
	"bookmargin": 1,
	"bookguttermargin": 1.2,
	"bleed": 0.125,
	"pixelsperunit": 72,
	"captionheight": 1,
	"cssstyles": "",
	"npoems": 80,
	"nstanzas": 3,
	"nlines": 4,
	"nchars": 48,
	"bookobj": {
		"title": "netfactory",
		"subtitle": "Sat Jan 20 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://netfactory.work",
		"authorurl": "https://mctavish.work/index.html",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"sections": [],
		"poemids": [],
		"bookunits": "in",
		"bookwidth": 8,
		"bookheight": 8,
		"bookmargin": 1,
		"bookguttermargin": 1.2,
		"bleed": 0.125,
		"pixelsperunit": 72,
		"captionheight": 1,
		"cssstyles": ""
	},
	"filmobj": {
		"title": "noise factory",
		"subtitle": "Sat Jan 20 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://noisefactory.work",
		"authorurl": "https://mctavish.work/index.html",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"sections": [],
		"poemids": [],
		"bookmargin": 1,
		"bookguttermargin": 1.2,
		"bleed": 0.125,
		"bookunits": "in",
		"bookwidth": 8,
		"bookheight": 8,
		"pixelsperunit": 72,
		"captionheight": 1,
		"cssstyles": ""
	}
};
module.exports = input;
